sudo: required
services: 
    -docker

before_install:
    - docker build -t jiaenpan/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true jiaenpan/react-test npm test -- --coverage 

after_success:
    - docker build -t jiaenpan/multi-client ./client
    - docker build -t jiaenpan/multi-nginx ./nginx
    - docker build -t jiaenpan/multi-server ./server
    - docker build -t jiaenpan/multi-worker ./worker
    # log in to docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
    # push image to docker hub
    - docker push jiaenpan/multi-client
    - docker push jiaenpan/multi-nginx
    - docker push jiaenpan/multi-server
    - docker push jiaenpan/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-180067870877
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ID
    secret_access_key:
        secret: $AWS_SECRET